version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - .:/django
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - web

  web:
    build: 
      context: .
      dockerfile: Dockerfile
    command: gunicorn movchatbot.wsgi:application --bind 0.0.0.0:3000
    volumes: 
      - .:/django/
    expose:
      - "3000"